# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoldenQuranSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoldenQuranSwift
  
  # Database Pod
  pod 'GRDB.swift'
  
  # Menu Pod
  pod 'SideMenu'
  
  # Keyboard Manager
  pod 'IQKeyboardManagerSwift'
  
#  # Date Relative
#  pod 'AFDateHelper'

end
