# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GoldenQuranSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoldenQuranSwift
  
  # Database Pod
  #pod 'GRDB.swift'
  use_frameworks!
  pod 'GRDB.swift' #, :git => 'https://github.com/groue/GRDB.swift.git', :branch => 'Swift3'
  
  # Menu Pod
  pod 'SideMenu'
#  pod 'SideMenuController'

  # Keyboard Manager
  pod 'IQKeyboardManagerSwift'
  
  #PrayerTimes
  pod 'Adhan'
  
#  # Date Relative // Moved to local file
#  pod 'AFDateHelper'

  # MoviePlayer
  #pod 'MobilePlayer'

end
